<?php

namespace Database\Seeders;

use App\Models\Daira;
use Illuminate\Database\Seeder;

class DairaSeeder extends Seeder
{
    private $dairas = [
        [
            'id' => 0,
            'arName' => 'أدرار',
            'name' => 'Adrar',
            'wilaya_id' => '01',
        ],
        [
            'id' => 1,
            'arName' => 'أولف',
            'name' => 'Aoulef',
            'wilaya_id' => '01',
        ],
        [
            'id' => 2,
            'arName' => 'أوقروت',
            'name' => 'Aougrout',
            'wilaya_id' => '49',
        ],
        [
            'id' => 3,
            'arName' => 'برج باجي مختار',
            'name' => 'Bordj Badji Mokhtar',
            'wilaya_id' => '50',
        ],
        [
            'id' => 4,
            'arName' => 'شروين',
            'name' => 'Charouine',
            'wilaya_id' => '49',
        ],
        [
            'id' => 5,
            'arName' => 'فنوغيل',
            'name' => 'Fenoughil',
            'wilaya_id' => '01',
        ],
        [
            'id' => 6,
            'arName' => 'زاوية كنتة',
            'name' => 'Zaouiat Kounta',
            'wilaya_id' => '01',
        ],
        [
            'id' => 7,
            'arName' => 'تنركوك',
            'name' => 'Tinerkouk',
            'wilaya_id' => '49',
        ],
        [
            'id' => 8,
            'arName' => 'تيميمون',
            'name' => 'Timimoun',
            'wilaya_id' => '49',
        ],
        [
            'id' => 9,
            'arName' => 'رقان',
            'name' => 'Reggane',
            'wilaya_id' => '01',
        ],
        [
            'id' => 10,
            'arName' => 'تسابيت',
            'name' => 'Tsabit',
            'wilaya_id' => '01',
        ],
        [
            'id' => 11,
            'arName' => 'أبو الحسن',
            'name' => 'Abou El Hassane',
            'wilaya_id' => '02',
        ],
        [
            'id' => 12,
            'arName' => 'عين مران',
            'name' => 'Ain Merane',
            'wilaya_id' => '02',
        ],
        [
            'id' => 13,
            'arName' => 'الزبوجة',
            'name' => 'Zeboudja',
            'wilaya_id' => '02',
        ],
        [
            'id' => 14,
            'arName' => 'الكريمية',
            'name' => 'El Karimia',
            'wilaya_id' => '02',
        ],
        [
            'id' => 15,
            'arName' => 'بني حواء',
            'name' => 'Beni Haoua',
            'wilaya_id' => '02',
        ],
        [
            'id' => 16,
            'arName' => 'وادي الفضة',
            'name' => 'Oued Fodda',
            'wilaya_id' => '02',
        ],
        [
            'id' => 17,
            'arName' => 'بوقادير',
            'name' => 'Boukadir',
            'wilaya_id' => '02',
        ],
        [
            'id' => 18,
            'arName' => 'أولاد فارس',
            'name' => 'Ouled Fares',
            'wilaya_id' => '02',
        ],
        [
            'id' => 19,
            'arName' => 'الشلف',
            'name' => 'Chlef',
            'wilaya_id' => '02',
        ],
        [
            'id' => 20,
            'arName' => 'تاوقريت',
            'name' => 'Taougrit',
            'wilaya_id' => '02',
        ],
        [
            'id' => 21,
            'arName' => 'أولاد بن عبد القادر',
            'name' => 'Ouled Ben Abdelkader',
            'wilaya_id' => '02',
        ],
        [
            'id' => 22,
            'arName' => 'المرسى',
            'name' => 'El Marsa',
            'wilaya_id' => '02',
        ],
        [
            'id' => 23,
            'arName' => 'تنس',
            'name' => 'Tenes',
            'wilaya_id' => '02',
        ],
        [
            'id' => 24,
            'arName' => 'أفلو',
            'name' => 'Aflou',
            'wilaya_id' => '03',
        ],
        [
            'id' => 25,
            'arName' => 'عين ماضي',
            'name' => 'Ain Madhi',
            'wilaya_id' => '03',
        ],
        [
            'id' => 26,
            'arName' => 'قتلة سيدي سعيد',
            'name' => 'Gueltat Sidi Saad',
            'wilaya_id' => '03',
        ],
        [
            'id' => 27,
            'arName' => 'قصر الحيران',
            'name' => 'Ksar El Hirane',
            'wilaya_id' => '03',
        ],
        [
            'id' => 28,
            'arName' => 'بريدة',
            'name' => 'Brida',
            'wilaya_id' => '03',
        ],
        [
            'id' => 29,
            'arName' => 'سيدي مخلوف',
            'name' => 'Sidi Makhlouf',
            'wilaya_id' => '03',
        ],
        [
            'id' => 30,
            'arName' => 'الغيشة',
            'name' => 'El Ghicha',
            'wilaya_id' => '03',
        ],
        [
            'id' => 31,
            'arName' => 'حاسي الرمل',
            'name' => "Hassi R'mel",
            'wilaya_id' => '03',
        ],
        [
            'id' => 32,
            'arName' => 'الأغواط',
            'name' => 'Laghouat',
            'wilaya_id' => '03',
        ],
        [
            'id' => 33,
            'arName' => 'وادي مرة',
            'name' => 'Oued Morra',
            'wilaya_id' => '03',
        ],
        [
            'id' => 34,
            'arName' => 'عين ببوش',
            'name' => 'Ain Babouche',
            'wilaya_id' => '04',
        ],
        [
            'id' => 35,
            'arName' => 'عين البيضاء',
            'name' => 'Ain Beida',
            'wilaya_id' => '04',
        ],
        [
            'id' => 36,
            'arName' => 'عين فكرون',
            'name' => 'Ain Fekroun',
            'wilaya_id' => '04',
        ],
        [
            'id' => 37,
            'arName' => 'عين كرشة',
            'name' => 'Ain Kercha',
            'wilaya_id' => '04',
        ],
        [
            'id' => 38,
            'arName' => 'عين مليلة',
            'name' => "Ain M'lila",
            'wilaya_id' => '04',
        ],
        [
            'id' => 39,
            'arName' => 'أم البواقي',
            'name' => 'Oum El Bouaghi',
            'wilaya_id' => '04',
        ],
        [
            'id' => 40,
            'arName' => 'مسكيانة',
            'name' => 'Meskiana',
            'wilaya_id' => '04',
        ],
        [
            'id' => 41,
            'arName' => 'سوق نعمان',
            'name' => 'Souk Naamane',
            'wilaya_id' => '04',
        ],
        [
            'id' => 42,
            'arName' => 'الضلعة',
            'name' => 'Dhalaa',
            'wilaya_id' => '04',
        ],
        [
            'id' => 43,
            'arName' => 'سيقوس',
            'name' => 'Sigus',
            'wilaya_id' => '04',
        ],
        [
            'id' => 44,
            'arName' => 'فكيرينة',
            'name' => "F'kirina",
            'wilaya_id' => '04',
        ],
        [
            'id' => 45,
            'arName' => 'قصر الصباحي',
            'name' => 'Ksar Sbahi',
            'wilaya_id' => '04',
        ],
        [
            'id' => 46,
            'arName' => 'عين جاسر',
            'name' => 'Ain Djasser',
            'wilaya_id' => '05',
        ],
        [
            'id' => 47,
            'arName' => 'عين التوتة',
            'name' => 'Ain Touta',
            'wilaya_id' => '05',
        ],
        [
            'id' => 48,
            'arName' => 'المعذر',
            'name' => 'El Madher',
            'wilaya_id' => '05',
        ],
        [
            'id' => 49,
            'arName' => 'أريس',
            'name' => 'Arris',
            'wilaya_id' => '05',
        ],
        [
            'id' => 50,
            'arName' => 'الجزار',
            'name' => 'Djezzar',
            'wilaya_id' => '05',
        ],
        [
            'id' => 51,
            'arName' => 'بريكة',
            'name' => 'Barika',
            'wilaya_id' => '05',
        ],
        [
            'id' => 52,
            'arName' => 'باتنة',
            'name' => 'Batna',
            'wilaya_id' => '05',
        ],
        [
            'id' => 53,
            'arName' => 'الشمرة',
            'name' => 'Chemora',
            'wilaya_id' => '05',
        ],
        [
            'id' => 54,
            'arName' => 'نقاوس',
            'name' => "N'gaous",
            'wilaya_id' => '05',
        ],
        [
            'id' => 55,
            'arName' => 'بوزينة',
            'name' => 'Bouzina',
            'wilaya_id' => '05',
        ],
        [
            'id' => 56,
            'arName' => 'ثنية العابد',
            'name' => 'Theniet El Abed',
            'wilaya_id' => '05',
        ],
        [
            'id' => 57,
            'arName' => 'إشمول',
            'name' => 'Ichemoul',
            'wilaya_id' => '05',
        ],
        [
            'id' => 58,
            'arName' => 'تكوت',
            'name' => 'Tkout',
            'wilaya_id' => '05',
        ],
        [
            'id' => 59,
            'arName' => 'رأس العيون',
            'name' => 'Ras El Aioun',
            'wilaya_id' => '05',
        ],
        [
            'id' => 60,
            'arName' => 'مروانة',
            'name' => 'Merouana',
            'wilaya_id' => '05',
        ],
        [
            'id' => 61,
            'arName' => 'سريانة',
            'name' => 'Seriana',
            'wilaya_id' => '05',
        ],
        [
            'id' => 62,
            'arName' => 'أولاد سي سليمان',
            'name' => 'Ouled Si Slimane',
            'wilaya_id' => '05',
        ],
        [
            'id' => 63,
            'arName' => 'منعة',
            'name' => 'Menaa',
            'wilaya_id' => '05',
        ],
        [
            'id' => 64,
            'arName' => 'تيمقاد',
            'name' => 'Timgad',
            'wilaya_id' => '05',
        ],
        [
            'id' => 65,
            'arName' => 'تازولت',
            'name' => 'Tazoult',
            'wilaya_id' => '05',
        ],
        [
            'id' => 66,
            'arName' => 'سقانة',
            'name' => 'Seggana',
            'wilaya_id' => '05',
        ],
        [
            'id' => 67,
            'arName' => 'أدكار',
            'name' => 'Adekar',
            'wilaya_id' => '06',
        ],
        [
            'id' => 68,
            'arName' => 'إغيل علي',
            'name' => 'Ighil Ali',
            'wilaya_id' => '06',
        ],
        [
            'id' => 69,
            'arName' => 'درقينة',
            'name' => 'Darguina',
            'wilaya_id' => '06',
        ],
        [
            'id' => 70,
            'arName' => 'أقبو',
            'name' => 'Akbou',
            'wilaya_id' => '06',
        ],
        [
            'id' => 71,
            'arName' => 'شميني',
            'name' => 'Chemini',
            'wilaya_id' => '06',
        ],
        [
            'id' => 72,
            'arName' => 'صدوق',
            'name' => 'Seddouk',
            'wilaya_id' => '06',
        ],
        [
            'id' => 73,
            'arName' => 'أميزور',
            'name' => 'Amizour',
            'wilaya_id' => '06',
        ],
        [
            'id' => 74,
            'arName' => 'أوقاس',
            'name' => 'Aokas',
            'wilaya_id' => '06',
        ],
        [
            'id' => 75,
            'arName' => 'برباشة',
            'name' => 'Barbacha',
            'wilaya_id' => '06',
        ],
        [
            'id' => 76,
            'arName' => 'بجاية',
            'name' => 'Bejaia',
            'wilaya_id' => '06',
        ],
        [
            'id' => 77,
            'arName' => 'تازملت',
            'name' => 'Tazmalt',
            'wilaya_id' => '06',
        ],
        [
            'id' => 78,
            'arName' => 'بني معوش',
            'name' => 'Beni Maouche',
            'wilaya_id' => '06',
        ],
        [
            'id' => 79,
            'arName' => 'تيشي',
            'name' => 'Tichy',
            'wilaya_id' => '06',
        ],
        [
            'id' => 80,
            'arName' => 'خراطة',
            'name' => 'Kherrata',
            'wilaya_id' => '06',
        ],
        [
            'id' => 81,
            'arName' => 'سيدي عيش',
            'name' => 'Sidi Aich',
            'wilaya_id' => '06',
        ],
        [
            'id' => 82,
            'arName' => 'القصر',
            'name' => 'El Kseur',
            'wilaya_id' => '06',
        ],
        [
            'id' => 83,
            'arName' => 'إفري أوزلاقن',
            'name' => 'Ifri Ouzellaguene',
            'wilaya_id' => '06',
        ],
        [
            'id' => 84,
            'arName' => 'سوق الإثنين',
            'name' => 'Souk El Tenine',
            'wilaya_id' => '06',
        ],
        [
            'id' => 85,
            'arName' => 'تيمزريت',
            'name' => 'Timezrit',
            'wilaya_id' => '06',
        ],
        [
            'id' => 86,
            'arName' => 'سيدي عقبة',
            'name' => 'Sidi Okba',
            'wilaya_id' => '07',
        ],
        [
            'id' => 87,
            'arName' => 'القنطرة',
            'name' => 'El Kantara',
            'wilaya_id' => '07',
        ],
        [
            'id' => 88,
            'arName' => 'سيدي خالد',
            'name' => 'Sidi Khaled',
            'wilaya_id' => '51',
        ],
        [
            'id' => 89,
            'arName' => 'بسكرة',
            'name' => 'Biskra',
            'wilaya_id' => '07',
        ],
        [
            'id' => 90,
            'arName' => 'طولقة',
            'name' => 'Tolga',
            'wilaya_id' => '07',
        ],
        [
            'id' => 91,
            'arName' => 'جمورة',
            'name' => 'Djemorah',
            'wilaya_id' => '07',
        ],
        [
            'id' => 92,
            'arName' => 'أولاد جلال',
            'name' => 'Ouled Djellal',
            'wilaya_id' => '51',
        ],
        [
            'id' => 93,
            'arName' => 'زريبة الوادي',
            'name' => 'Zeribet El Oued',
            'wilaya_id' => '07',
        ],
        [
            'id' => 94,
            'arName' => 'فوغالة',
            'name' => 'Foughala',
            'wilaya_id' => '07',
        ],
        [
            'id' => 95,
            'arName' => 'الوطاية',
            'name' => 'El Outaya',
            'wilaya_id' => '07',
        ],
        [
            'id' => 96,
            'arName' => 'أورلال',
            'name' => 'Ourlal',
            'wilaya_id' => '07',
        ],
        [
            'id' => 97,
            'arName' => 'مشونش',
            'name' => 'Mechouneche',
            'wilaya_id' => '07',
        ],
        [
            'id' => 98,
            'arName' => 'العبادلة',
            'name' => 'Abadla',
            'wilaya_id' => '08',
        ],
        [
            'id' => 99,
            'arName' => 'بشار',
            'name' => 'Bechar',
            'wilaya_id' => '08',
        ],
        [
            'id' => 100,
            'arName' => 'بني عباس',
            'name' => 'Beni Abbes',
            'wilaya_id' => '52',
        ],
        [
            'id' => 101,
            'arName' => 'كرزاز',
            'name' => 'Kerzaz',
            'wilaya_id' => '52',
        ],
        [
            'id' => 102,
            'arName' => 'بني ونيف',
            'name' => 'Beni Ounif',
            'wilaya_id' => '08',
        ],
        [
            'id' => 103,
            'arName' => 'لحمر',
            'name' => 'Lahmar',
            'wilaya_id' => '08',
        ],
        [
            'id' => 104,
            'arName' => 'الواتة',
            'name' => 'El Ouata',
            'wilaya_id' => '52',
        ],
        [
            'id' => 105,
            'arName' => 'إقلي',
            'name' => 'Igli',
            'wilaya_id' => '52',
        ],
        [
            'id' => 106,
            'arName' => 'القنادسة',
            'name' => 'Kenadsa',
            'wilaya_id' => '08',
        ],
        [
            'id' => 107,
            'arName' => 'أولاد خضير',
            'name' => 'Ouled Khodeir',
            'wilaya_id' => '52',
        ],
        [
            'id' => 108,
            'arName' => 'تبلبالة',
            'name' => 'Tabelbala',
            'wilaya_id' => '08',
        ],
        [
            'id' => 109,
            'arName' => 'تاغيت',
            'name' => 'Taghit',
            'wilaya_id' => '08',
        ],
        [
            'id' => 110,
            'arName' => 'موزاية',
            'name' => 'Mouzaia',
            'wilaya_id' => '09',
        ],
        [
            'id' => 111,
            'arName' => 'أولاد يعيش',
            'name' => 'Ouled Yaich',
            'wilaya_id' => '09',
        ],
        [
            'id' => 112,
            'arName' => 'وادي العلايق',
            'name' => 'Oued El Alleug',
            'wilaya_id' => '09',
        ],
        [
            'id' => 113,
            'arName' => 'البليدة',
            'name' => 'Blida',
            'wilaya_id' => '09',
        ],
        [
            'id' => 114,
            'arName' => 'بوفاريك',
            'name' => 'Boufarik',
            'wilaya_id' => '09',
        ],
        [
            'id' => 115,
            'arName' => 'بوقرة',
            'name' => 'Bougara',
            'wilaya_id' => '09',
        ],
        [
            'id' => 116,
            'arName' => 'بوعينان',
            'name' => 'Bouinan',
            'wilaya_id' => '09',
        ],
        [
            'id' => 117,
            'arName' => 'مفتاح',
            'name' => 'Meftah',
            'wilaya_id' => '09',
        ],
        [
            'id' => 118,
            'arName' => 'العفرون',
            'name' => 'El Affroun',
            'wilaya_id' => '09',
        ],
        [
            'id' => 119,
            'arName' => 'الأربعاء',
            'name' => 'Larbaa',
            'wilaya_id' => '09',
        ],
        [
            'id' => 120,
            'arName' => 'مشد الله',
            'name' => "M'chedallah",
            'wilaya_id' => '10',
        ],
        [
            'id' => 121,
            'arName' => 'بشلول',
            'name' => 'Bechloul',
            'wilaya_id' => '10',
        ],
        [
            'id' => 122,
            'arName' => 'عين بسام',
            'name' => 'Ain Bessem',
            'wilaya_id' => '10',
        ],
        [
            'id' => 123,
            'arName' => 'البويرة',
            'name' => 'Bouira',
            'wilaya_id' => '10',
        ],
        [
            'id' => 124,
            'arName' => 'القادرية',
            'name' => 'Kadiria',
            'wilaya_id' => '10',
        ],
        [
            'id' => 125,
            'arName' => 'بئر غبالو',
            'name' => 'Bir Ghbalou',
            'wilaya_id' => '10',
        ],
        [
            'id' => 126,
            'arName' => 'برج أوخريص',
            'name' => 'Bordj Okhriss',
            'wilaya_id' => '10',
        ],
        [
            'id' => 127,
            'arName' => 'الأخضرية',
            'name' => 'Lakhdaria',
            'wilaya_id' => '10',
        ],
        [
            'id' => 128,
            'arName' => 'سور الغزلان',
            'name' => 'Sour El Ghozlane',
            'wilaya_id' => '10',
        ],
        [
            'id' => 129,
            'arName' => 'الهاشمية',
            'name' => 'El Hachimia',
            'wilaya_id' => '10',
        ],
        [
            'id' => 130,
            'arName' => 'سوق الخميس',
            'name' => 'Souk El Khemis',
            'wilaya_id' => '10',
        ],
        [
            'id' => 131,
            'arName' => 'الحيزر',
            'name' => 'Haizer',
            'wilaya_id' => '10',
        ],
        [
            'id' => 132,
            'arName' => 'سيلت',
            'name' => 'Silet',
            'wilaya_id' => '11',
        ],
        [
            'id' => 133,
            'arName' => 'تمنراست',
            'name' => 'Tamanrasset',
            'wilaya_id' => '11',
        ],
        [
            'id' => 134,
            'arName' => 'عين قزام',
            'name' => 'In Guezzam',
            'wilaya_id' => '54',
        ],
        [
            'id' => 135,
            'arName' => 'عين صالح',
            'name' => 'In Salah',
            'wilaya_id' => '53',
        ],
        [
            'id' => 136,
            'arName' => 'تاظروك',
            'name' => 'Tazrouk',
            'wilaya_id' => '11',
        ],
        [
            'id' => 137,
            'arName' => 'إينغر',
            'name' => 'In Ghar',
            'wilaya_id' => '53',
        ],
        [
            'id' => 138,
            'arName' => 'تين زواتين',
            'name' => 'Tin Zouatine',
            'wilaya_id' => '54',
        ],
        [
            'id' => 139,
            'arName' => 'الونزة',
            'name' => 'Ouenza',
            'wilaya_id' => '12',
        ],
        [
            'id' => 140,
            'arName' => 'العقلة',
            'name' => 'El Ogla',
            'wilaya_id' => '12',
        ],
        [
            'id' => 141,
            'arName' => 'الكويف',
            'name' => 'El Kouif',
            'wilaya_id' => '12',
        ],
        [
            'id' => 142,
            'arName' => 'مرسط',
            'name' => 'Morsott',
            'wilaya_id' => '12',
        ],
        [
            'id' => 143,
            'arName' => 'بئر مقدم',
            'name' => 'Bir Mokadem',
            'wilaya_id' => '12',
        ],
        [
            'id' => 144,
            'arName' => 'بئر العاتر',
            'name' => 'Bir El Ater',
            'wilaya_id' => '12',
        ],
        [
            'id' => 145,
            'arName' => 'العوينات',
            'name' => 'El Aouinet',
            'wilaya_id' => '12',
        ],
        [
            'id' => 146,
            'arName' => 'الشريعة',
            'name' => 'Cheria',
            'wilaya_id' => '12',
        ],
        [
            'id' => 147,
            'arName' => 'الماء الابيض',
            'name' => 'El Malabiod',
            'wilaya_id' => '12',
        ],
        [
            'id' => 148,
            'arName' => 'نقرين',
            'name' => 'Negrine',
            'wilaya_id' => '12',
        ],
        [
            'id' => 149,
            'arName' => 'أم علي',
            'name' => 'Oum Ali',
            'wilaya_id' => '12',
        ],
        [
            'id' => 150,
            'arName' => 'تبسة',
            'name' => 'Tebessa',
            'wilaya_id' => '12',
        ],
        [
            'id' => 151,
            'arName' => 'فلاوسن',
            'name' => 'Fellaoucene',
            'wilaya_id' => '13',
        ],
        [
            'id' => 152,
            'arName' => 'شتوان',
            'name' => 'Chetouane',
            'wilaya_id' => '13',
        ],
        [
            'id' => 153,
            'arName' => 'منصورة',
            'name' => 'Mansourah',
            'wilaya_id' => '13',
        ],
        [
            'id' => 154,
            'arName' => 'عين تالوت',
            'name' => 'Ain Tellout',
            'wilaya_id' => '13',
        ],
        [
            'id' => 155,
            'arName' => 'الرمشي',
            'name' => 'Remchi',
            'wilaya_id' => '13',
        ],
        [
            'id' => 156,
            'arName' => 'باب العسة',
            'name' => 'Bab El Assa',
            'wilaya_id' => '13',
        ],
        [
            'id' => 157,
            'arName' => 'بني سنوس',
            'name' => 'Beni Snous',
            'wilaya_id' => '13',
        ],
        [
            'id' => 158,
            'arName' => 'بني بوسعيد',
            'name' => 'Beni Boussaid',
            'wilaya_id' => '13',
        ],
        [
            'id' => 159,
            'arName' => 'هنين',
            'name' => 'Honnaine',
            'wilaya_id' => '13',
        ],
        [
            'id' => 160,
            'arName' => 'أولاد ميمون',
            'name' => 'Ouled Mimoun',
            'wilaya_id' => '13',
        ],
        [
            'id' => 161,
            'arName' => 'بن سكران',
            'name' => 'Bensekrane',
            'wilaya_id' => '13',
        ],
        [
            'id' => 162,
            'arName' => 'صبرة',
            'name' => 'Sabra',
            'wilaya_id' => '13',
        ],
        [
            'id' => 163,
            'arName' => 'سيدي الجيلالي',
            'name' => 'Sidi Djillali',
            'wilaya_id' => '13',
        ],
        [
            'id' => 164,
            'arName' => 'الغزوات',
            'name' => 'Ghazaouet',
            'wilaya_id' => '13',
        ],
        [
            'id' => 165,
            'arName' => 'ندرومة',
            'name' => 'Nedroma',
            'wilaya_id' => '13',
        ],
        [
            'id' => 166,
            'arName' => 'سبدو',
            'name' => 'Sebdou',
            'wilaya_id' => '13',
        ],
        [
            'id' => 167,
            'arName' => 'مغنية',
            'name' => 'Maghnia',
            'wilaya_id' => '13',
        ],
        [
            'id' => 168,
            'arName' => 'الحناية',
            'name' => 'Hennaya',
            'wilaya_id' => '13',
        ],
        [
            'id' => 169,
            'arName' => 'مرسى بن مهيدي',
            'name' => 'Marsa Ben Mehdi',
            'wilaya_id' => '13',
        ],
        [
            'id' => 170,
            'arName' => 'تلمسان',
            'name' => 'Tlemcen',
            'wilaya_id' => '13',
        ],
        [
            'id' => 171,
            'arName' => 'دحموني',
            'name' => 'Dahmouni',
            'wilaya_id' => '14',
        ],
        [
            'id' => 172,
            'arName' => 'عين الذهب',
            'name' => 'Ain Deheb',
            'wilaya_id' => '14',
        ],
        [
            'id' => 173,
            'arName' => 'مهدية',
            'name' => 'Mahdia',
            'wilaya_id' => '14',
        ],
        [
            'id' => 174,
            'arName' => 'فرندة',
            'name' => 'Frenda',
            'wilaya_id' => '14',
        ],
        [
            'id' => 175,
            'arName' => 'عين كرمس',
            'name' => 'Ain Kermes',
            'wilaya_id' => '14',
        ],
        [
            'id' => 176,
            'arName' => 'حمادية',
            'name' => 'Hamadia',
            'wilaya_id' => '14',
        ],
        [
            'id' => 177,
            'arName' => 'مشرع الصفا',
            'name' => 'Mechraa Sfa',
            'wilaya_id' => '14',
        ],
        [
            'id' => 178,
            'arName' => 'السوقر',
            'name' => 'Sougueur',
            'wilaya_id' => '14',
        ],
        [
            'id' => 179,
            'arName' => 'رحوية',
            'name' => 'Rahouia',
            'wilaya_id' => '14',
        ],
        [
            'id' => 180,
            'arName' => 'قصر الشلالة',
            'name' => 'Ksar Chellala',
            'wilaya_id' => '14',
        ],
        [
            'id' => 181,
            'arName' => 'مدروسة',
            'name' => 'Medroussa',
            'wilaya_id' => '14',
        ],
        [
            'id' => 182,
            'arName' => 'مغيلة',
            'name' => 'Meghila',
            'wilaya_id' => '14',
        ],
        [
            'id' => 183,
            'arName' => 'وادي ليلي',
            'name' => 'Oued Lili',
            'wilaya_id' => '14',
        ],
        [
            'id' => 184,
            'arName' => 'تيارت',
            'name' => 'Tiaret',
            'wilaya_id' => '14',
        ],
        [
            'id' => 185,
            'arName' => 'عين الحمام',
            'name' => 'Ain El Hammam',
            'wilaya_id' => '15',
        ],
        [
            'id' => 186,
            'arName' => 'أزفون',
            'name' => 'Azeffoun',
            'wilaya_id' => '15',
        ],
        [
            'id' => 187,
            'arName' => 'واضية',
            'name' => 'Ouadhias',
            'wilaya_id' => '15',
        ],
        [
            'id' => 188,
            'arName' => 'ذراع الميزان',
            'name' => 'Draa El Mizan',
            'wilaya_id' => '15',
        ],
        [
            'id' => 189,
            'arName' => 'الأربعاء ناث إيراثن',
            'name' => 'Larbaa Nath Iraten',
            'wilaya_id' => '15',
        ],
        [
            'id' => 190,
            'arName' => 'واسيف',
            'name' => 'Ouacif',
            'wilaya_id' => '15',
        ],
        [
            'id' => 191,
            'arName' => 'مقلع',
            'name' => 'Mekla',
            'wilaya_id' => '15',
        ],
        [
            'id' => 192,
            'arName' => 'واقنون',
            'name' => 'Ouaguenoun',
            'wilaya_id' => '15',
        ],
        [
            'id' => 193,
            'arName' => 'بني دوالة',
            'name' => 'Beni Douala',
            'wilaya_id' => '15',
        ],
        [
            'id' => 194,
            'arName' => 'تيزي راشد',
            'name' => 'Tizi Rached',
            'wilaya_id' => '15',
        ],
        [
            'id' => 195,
            'arName' => 'بوغني',
            'name' => 'Boghni',
            'wilaya_id' => '15',
        ],
        [
            'id' => 196,
            'arName' => 'عزازقة',
            'name' => 'Azazga',
            'wilaya_id' => '15',
        ],
        [
            'id' => 197,
            'arName' => 'بني يني',
            'name' => 'Benni Yenni',
            'wilaya_id' => '15',
        ],
        [
            'id' => 198,
            'arName' => 'بوزقن',
            'name' => 'Bouzeguene',
            'wilaya_id' => '15',
        ],
        [
            'id' => 199,
            'arName' => 'ماكودة',
            'name' => 'Makouda',
            'wilaya_id' => '15',
        ],
        [
            'id' => 200,
            'arName' => 'ذراع بن خدة',
            'name' => 'Draa Ben Khedda',
            'wilaya_id' => '15',
        ],
        [
            'id' => 201,
            'arName' => 'إفرحونان',
            'name' => 'Iferhounene',
            'wilaya_id' => '15',
        ],
        [
            'id' => 202,
            'arName' => 'تيقزيرت',
            'name' => 'Tigzirt',
            'wilaya_id' => '15',
        ],
        [
            'id' => 203,
            'arName' => 'معاتقة',
            'name' => 'Maatkas',
            'wilaya_id' => '15',
        ],
        [
            'id' => 204,
            'arName' => 'تيزي غنيف',
            'name' => 'Tizi-Ghenif',
            'wilaya_id' => '15',
        ],
        [
            'id' => 205,
            'arName' => 'تيزي وزو',
            'name' => 'Tizi Ouzou',
            'wilaya_id' => '15',
        ],
        [
            'id' => 206,
            'arName' => 'الشراقة',
            'name' => 'Cheraga',
            'wilaya_id' => '16',
        ],
        [
            'id' => 207,
            'arName' => 'الدار البيضاء',
            'name' => 'Dar El Beida',
            'wilaya_id' => '16',
        ],
        [
            'id' => 208,
            'arName' => 'سيدي امحمد',
            'name' => "Sidi M'hamed",
            'wilaya_id' => '16',
        ],
        [
            'id' => 209,
            'arName' => 'باب الوادي',
            'name' => 'Bab El Oued',
            'wilaya_id' => '16',
        ],
        [
            'id' => 210,
            'arName' => 'الدرارية',
            'name' => 'Draria',
            'wilaya_id' => '16',
        ],
        [
            'id' => 211,
            'arName' => 'الحراش',
            'name' => 'El Harrach',
            'wilaya_id' => '16',
        ],
        [
            'id' => 212,
            'arName' => 'براقي',
            'name' => 'Baraki',
            'wilaya_id' => '16',
        ],
        [
            'id' => 213,
            'arName' => 'بوزريعة',
            'name' => 'Bouzareah',
            'wilaya_id' => '16',
        ],
        [
            'id' => 214,
            'arName' => 'بئر مراد رايس',
            'name' => 'Bir Mourad Rais',
            'wilaya_id' => '16',
        ],
        [
            'id' => 215,
            'arName' => 'بئر توتة',
            'name' => 'Birtouta',
            'wilaya_id' => '16',
        ],
        [
            'id' => 216,
            'arName' => 'حسين داي',
            'name' => 'Hussein Dey',
            'wilaya_id' => '16',
        ],
        [
            'id' => 217,
            'arName' => 'الرويبة',
            'name' => 'Rouiba',
            'wilaya_id' => '16',
        ],
        [
            'id' => 218,
            'arName' => 'زرالدة',
            'name' => 'Zeralda',
            'wilaya_id' => '16',
        ],
        [
            'id' => 219,
            'arName' => 'الادريسية',
            'name' => 'El Idrissia',
            'wilaya_id' => '17',
        ],
        [
            'id' => 220,
            'arName' => 'عين الإبل',
            'name' => 'Ain El Ibel',
            'wilaya_id' => '17',
        ],
        [
            'id' => 221,
            'arName' => 'حد الصحاري',
            'name' => 'Had Sahary',
            'wilaya_id' => '17',
        ],
        [
            'id' => 222,
            'arName' => 'حاسي بحبح',
            'name' => 'Hassi Bahbah',
            'wilaya_id' => '17',
        ],
        [
            'id' => 223,
            'arName' => 'عين وسارة',
            'name' => 'Ain Oussera',
            'wilaya_id' => '17',
        ],
        [
            'id' => 224,
            'arName' => 'فيض البطمة',
            'name' => 'Faidh El Botma',
            'wilaya_id' => '17',
        ],
        [
            'id' => 225,
            'arName' => 'بيرين',
            'name' => 'Birine',
            'wilaya_id' => '17',
        ],
        [
            'id' => 226,
            'arName' => 'الشارف',
            'name' => 'Charef',
            'wilaya_id' => '17',
        ],
        [
            'id' => 227,
            'arName' => 'دار الشيوخ',
            'name' => 'Dar Chioukh',
            'wilaya_id' => '17',
        ],
        [
            'id' => 228,
            'arName' => 'مسعد',
            'name' => 'Messaad',
            'wilaya_id' => '17',
        ],
        [
            'id' => 229,
            'arName' => 'الجلفة',
            'name' => 'Djelfa',
            'wilaya_id' => '17',
        ],
        [
            'id' => 230,
            'arName' => 'سيدي لعجال',
            'name' => 'Sidi Laadjel',
            'wilaya_id' => '17',
        ],
        [
            'id' => 231,
            'arName' => 'الشقفة',
            'name' => 'Chekfa',
            'wilaya_id' => '18',
        ],
        [
            'id' => 232,
            'arName' => 'جيملة',
            'name' => 'Djimla',
            'wilaya_id' => '18',
        ],
        [
            'id' => 233,
            'arName' => 'العنصر',
            'name' => 'El Ancer',
            'wilaya_id' => '18',
        ],
        [
            'id' => 234,
            'arName' => 'الطاهير',
            'name' => 'Taher',
            'wilaya_id' => '18',
        ],
        [
            'id' => 235,
            'arName' => 'العوانة',
            'name' => 'El Aouana',
            'wilaya_id' => '18',
        ],
        [
            'id' => 236,
            'arName' => 'الميلية',
            'name' => 'El Milia',
            'wilaya_id' => '18',
        ],
        [
            'id' => 237,
            'arName' => 'زيامة منصورية',
            'name' => 'Ziamah Mansouriah',
            'wilaya_id' => '18',
        ],
        [
            'id' => 238,
            'arName' => 'السطارة',
            'name' => 'Settara',
            'wilaya_id' => '18',
        ],
        [
            'id' => 239,
            'arName' => 'جيجل',
            'name' => 'Jijel',
            'wilaya_id' => '18',
        ],
        [
            'id' => 240,
            'arName' => 'تاكسنة',
            'name' => 'Texenna',
            'wilaya_id' => '18',
        ],
        [
            'id' => 241,
            'arName' => 'سيدي معروف',
            'name' => 'Sidi Marouf',
            'wilaya_id' => '18',
        ],
        [
            'id' => 242,
            'arName' => 'عين أرنات',
            'name' => 'Ain Arnat',
            'wilaya_id' => '19',
        ],
        [
            'id' => 243,
            'arName' => 'عين أزال',
            'name' => 'Ain Azel',
            'wilaya_id' => '19',
        ],
        [
            'id' => 244,
            'arName' => 'عين الكبيرة',
            'name' => 'Ain El Kebira',
            'wilaya_id' => '19',
        ],
        [
            'id' => 245,
            'arName' => 'عين ولمان',
            'name' => 'Ain Oulmene',
            'wilaya_id' => '19',
        ],
        [
            'id' => 246,
            'arName' => 'بني ورتيلان',
            'name' => 'Beni Ourtilane',
            'wilaya_id' => '19',
        ],
        [
            'id' => 247,
            'arName' => 'بوقاعة',
            'name' => 'Bougaa',
            'wilaya_id' => '19',
        ],
        [
            'id' => 248,
            'arName' => 'بني عزيز',
            'name' => 'Beni Aziz',
            'wilaya_id' => '19',
        ],
        [
            'id' => 249,
            'arName' => 'بوعنداس',
            'name' => 'Bouandas',
            'wilaya_id' => '19',
        ],
        [
            'id' => 250,
            'arName' => 'عموشة',
            'name' => 'Amoucha',
            'wilaya_id' => '19',
        ],
        [
            'id' => 251,
            'arName' => 'بابور',
            'name' => 'Babor',
            'wilaya_id' => '19',
        ],
        [
            'id' => 252,
            'arName' => 'العلمة',
            'name' => 'El Eulma',
            'wilaya_id' => '19',
        ],
        [
            'id' => 253,
            'arName' => 'بئر العرش',
            'name' => 'Bir El Arch',
            'wilaya_id' => '19',
        ],
        [
            'id' => 254,
            'arName' => 'جميلة',
            'name' => 'Djemila',
            'wilaya_id' => '19',
        ],
        [
            'id' => 255,
            'arName' => 'صالح باي',
            'name' => 'Salah Bey',
            'wilaya_id' => '19',
        ],
        [
            'id' => 256,
            'arName' => 'حمام قرقور',
            'name' => 'Hammam Guergour',
            'wilaya_id' => '19',
        ],
        [
            'id' => 257,
            'arName' => 'قنزات',
            'name' => 'Guenzet',
            'wilaya_id' => '19',
        ],
        [
            'id' => 258,
            'arName' => 'قجال',
            'name' => 'Guidjel',
            'wilaya_id' => '19',
        ],
        [
            'id' => 259,
            'arName' => 'حمام السخنة',
            'name' => 'Hammam Sokhna',
            'wilaya_id' => '19',
        ],
        [
            'id' => 260,
            'arName' => 'ماوكلان',
            'name' => 'Maoklane',
            'wilaya_id' => '19',
        ],
        [
            'id' => 261,
            'arName' => 'سطيف',
            'name' => 'Setif',
            'wilaya_id' => '19',
        ],
        [
            'id' => 262,
            'arName' => 'عين الحجر',
            'name' => 'Ain El Hadjar',
            'wilaya_id' => '20',
        ],
        [
            'id' => 263,
            'arName' => 'الحساسنة',
            'name' => 'El Hassasna',
            'wilaya_id' => '20',
        ],
        [
            'id' => 264,
            'arName' => 'أولاد ابراهيم',
            'name' => 'Ouled Brahim',
            'wilaya_id' => '20',
        ],
        [
            'id' => 265,
            'arName' => 'يوب',
            'name' => 'Youb',
            'wilaya_id' => '20',
        ],
        [
            'id' => 266,
            'arName' => 'سيدي بوبكر',
            'name' => 'Sidi Boubekeur',
            'wilaya_id' => '20',
        ],
        [
            'id' => 267,
            'arName' => 'سعيدة',
            'name' => 'Saida',
            'wilaya_id' => '20',
        ],
        [
            'id' => 268,
            'arName' => 'سيدي مزغيش',
            'name' => 'Sidi Mezghiche',
            'wilaya_id' => '21',
        ],
        [
            'id' => 269,
            'arName' => 'عزابة',
            'name' => 'Azzaba',
            'wilaya_id' => '21',
        ],
        [
            'id' => 270,
            'arName' => 'عين قشرة',
            'name' => 'Ain Kechra',
            'wilaya_id' => '21',
        ],
        [
            'id' => 271,
            'arName' => 'الحدائق',
            'name' => 'El Hadaiek',
            'wilaya_id' => '21',
        ],
        [
            'id' => 272,
            'arName' => 'بن عزوز',
            'name' => 'Ben Azzouz',
            'wilaya_id' => '21',
        ],
        [
            'id' => 273,
            'arName' => 'رمضان جمال',
            'name' => 'Ramdane Djamel',
            'wilaya_id' => '21',
        ],
        [
            'id' => 274,
            'arName' => 'القل',
            'name' => 'Collo',
            'wilaya_id' => '21',
        ],
        [
            'id' => 275,
            'arName' => 'تمالوس',
            'name' => 'Tamalous',
            'wilaya_id' => '21',
        ],
        [
            'id' => 276,
            'arName' => 'الحروش',
            'name' => 'El Harrouch',
            'wilaya_id' => '21',
        ],
        [
            'id' => 277,
            'arName' => 'سكيكدة',
            'name' => 'Skikda',
            'wilaya_id' => '21',
        ],
        [
            'id' => 278,
            'arName' => 'الزيتونة',
            'name' => 'Zitouna',
            'wilaya_id' => '21',
        ],
        [
            'id' => 279,
            'arName' => 'أولاد عطية',
            'name' => 'Ouled Attia',
            'wilaya_id' => '21',
        ],
        [
            'id' => 280,
            'arName' => 'أم الطوب',
            'name' => 'Oum Toub',
            'wilaya_id' => '21',
        ],
        [
            'id' => 281,
            'arName' => 'عين البرد',
            'name' => 'Ain El Berd',
            'wilaya_id' => '22',
        ],
        [
            'id' => 282,
            'arName' => 'سيدي علي بوسيدي',
            'name' => 'Sidi Ali Boussidi',
            'wilaya_id' => '22',
        ],
        [
            'id' => 283,
            'arName' => 'تسالة',
            'name' => 'Tessala',
            'wilaya_id' => '22',
        ],
        [
            'id' => 284,
            'arName' => 'مولاي سليسن',
            'name' => 'Moulay Slissen',
            'wilaya_id' => '22',
        ],
        [
            'id' => 285,
            'arName' => 'سفيزف',
            'name' => 'Sfisef',
            'wilaya_id' => '22',
        ],
        [
            'id' => 286,
            'arName' => 'سيدي لحسن',
            'name' => 'Sidi Lahcene',
            'wilaya_id' => '22',
        ],
        [
            'id' => 287,
            'arName' => 'بن باديس',
            'name' => 'Ben Badis',
            'wilaya_id' => '22',
        ],
        [
            'id' => 288,
            'arName' => 'مصطفى بن ابراهيم',
            'name' => 'Mostefa Ben Brahim',
            'wilaya_id' => '22',
        ],
        [
            'id' => 289,
            'arName' => 'تنيرة',
            'name' => 'Tenira',
            'wilaya_id' => '22',
        ],
        [
            'id' => 290,
            'arName' => 'مرحوم',
            'name' => 'Marhoum',
            'wilaya_id' => '22',
        ],
        [
            'id' => 291,
            'arName' => 'سيدي علي بن يوب',
            'name' => 'Sidi Ali Ben Youb',
            'wilaya_id' => '22',
        ],
        [
            'id' => 292,
            'arName' => 'تلاغ',
            'name' => 'Telagh',
            'wilaya_id' => '22',
        ],
        [
            'id' => 293,
            'arName' => 'مرين',
            'name' => 'Merine',
            'wilaya_id' => '22',
        ],
        [
            'id' => 294,
            'arName' => 'راس الماء',
            'name' => 'Ras El Ma',
            'wilaya_id' => '22',
        ],
        [
            'id' => 295,
            'arName' => 'سيدي بلعباس',
            'name' => 'Sidi Bel Abbes',
            'wilaya_id' => '22',
        ],
        [
            'id' => 296,
            'arName' => 'عين الباردة',
            'name' => 'Ain El Berda',
            'wilaya_id' => '23',
        ],
        [
            'id' => 297,
            'arName' => 'عنابة',
            'name' => 'Annaba',
            'wilaya_id' => '23',
        ],
        [
            'id' => 298,
            'arName' => 'برحال',
            'name' => 'Berrahal',
            'wilaya_id' => '23',
        ],
        [
            'id' => 299,
            'arName' => 'شطايبي',
            'name' => 'Chetaibi',
            'wilaya_id' => '23',
        ],
        [
            'id' => 300,
            'arName' => 'البوني',
            'name' => 'El Bouni',
            'wilaya_id' => '23',
        ],
        [
            'id' => 301,
            'arName' => 'الحجار',
            'name' => 'El Hadjar',
            'wilaya_id' => '23',
        ],
        [
            'id' => 302,
            'arName' => 'بوشقوف',
            'name' => 'Bouchegouf',
            'wilaya_id' => '24',
        ],
        [
            'id' => 303,
            'arName' => 'عين مخلوف',
            'name' => 'Ain Makhlouf',
            'wilaya_id' => '24',
        ],
        [
            'id' => 304,
            'arName' => 'وادي الزناتي',
            'name' => 'Oued Zenati',
            'wilaya_id' => '24',
        ],
        [
            'id' => 305,
            'arName' => 'خزارة',
            'name' => 'Khezaras',
            'wilaya_id' => '24',
        ],
        [
            'id' => 306,
            'arName' => 'قلعة بوصبع',
            'name' => 'Guelaat Bousbaa',
            'wilaya_id' => '24',
        ],
        [
            'id' => 307,
            'arName' => 'قالمة',
            'name' => 'Guelma',
            'wilaya_id' => '24',
        ],
        [
            'id' => 308,
            'arName' => 'حمام دباغ',
            'name' => 'Hammam Debagh',
            'wilaya_id' => '24',
        ],
        [
            'id' => 309,
            'arName' => 'هيليوبوليس',
            'name' => 'Heliopolis',
            'wilaya_id' => '24',
        ],
        [
            'id' => 310,
            'arName' => 'حمام النبايل',
            'name' => "Hammam N'bails",
            'wilaya_id' => '24',
        ],
        [
            'id' => 311,
            'arName' => 'عين حساينية',
            'name' => 'Ain Hessainia',
            'wilaya_id' => '24',
        ],
        [
            'id' => 312,
            'arName' => 'عين عبيد',
            'name' => 'Ain Abid',
            'wilaya_id' => '25',
        ],
        [
            'id' => 313,
            'arName' => 'الخروب',
            'name' => 'El Khroub',
            'wilaya_id' => '25',
        ],
        [
            'id' => 314,
            'arName' => 'زيغود يوسف',
            'name' => 'Zighoud Youcef',
            'wilaya_id' => '25',
        ],
        [
            'id' => 315,
            'arName' => 'قسنطينة',
            'name' => 'Constantine',
            'wilaya_id' => '25',
        ],
        [
            'id' => 316,
            'arName' => 'حامة بوزيان',
            'name' => 'Hamma Bouziane',
            'wilaya_id' => '25',
        ],
        [
            'id' => 317,
            'arName' => 'ابن زياد',
            'name' => 'Ibn Ziad',
            'wilaya_id' => '25',
        ],
        [
            'id' => 318,
            'arName' => 'عين بوسيف',
            'name' => 'Ain Boucif',
            'wilaya_id' => '26',
        ],
        [
            'id' => 319,
            'arName' => 'شلالة العذاورة',
            'name' => 'Chellalat El Adhaoura',
            'wilaya_id' => '26',
        ],
        [
            'id' => 320,
            'arName' => 'تابلاط',
            'name' => 'Tablat',
            'wilaya_id' => '26',
        ],
        [
            'id' => 321,
            'arName' => 'عزيز',
            'name' => 'Aziz',
            'wilaya_id' => '26',
        ],
        [
            'id' => 322,
            'arName' => 'العمارية',
            'name' => 'El Omaria',
            'wilaya_id' => '26',
        ],
        [
            'id' => 323,
            'arName' => 'وزرة',
            'name' => 'Ouzera',
            'wilaya_id' => '26',
        ],
        [
            'id' => 324,
            'arName' => 'بني سليمان',
            'name' => 'Beni Slimane',
            'wilaya_id' => '26',
        ],
        [
            'id' => 325,
            'arName' => 'البرواقية',
            'name' => 'Berrouaghia',
            'wilaya_id' => '26',
        ],
        [
            'id' => 326,
            'arName' => 'القلب الكبير',
            'name' => 'Guelb El Kebir',
            'wilaya_id' => '26',
        ],
        [
            'id' => 327,
            'arName' => 'أولاد عنتر',
            'name' => 'Ouled Antar',
            'wilaya_id' => '26',
        ],
        [
            'id' => 328,
            'arName' => 'الشهبونية',
            'name' => 'Chahbounia',
            'wilaya_id' => '26',
        ],
        [
            'id' => 329,
            'arName' => 'سي المحجوب',
            'name' => 'Si Mahdjoub',
            'wilaya_id' => '26',
        ],
        [
            'id' => 330,
            'arName' => 'سيدي نعمان',
            'name' => 'Sidi Naamane',
            'wilaya_id' => '26',
        ],
        [
            'id' => 331,
            'arName' => 'السواقي',
            'name' => 'Souaghi',
            'wilaya_id' => '26',
        ],
        [
            'id' => 332,
            'arName' => 'المدية',
            'name' => 'Medea',
            'wilaya_id' => '26',
        ],
        [
            'id' => 333,
            'arName' => 'العزيزية',
            'name' => 'El Azizia',
            'wilaya_id' => '26',
        ],
        [
            'id' => 334,
            'arName' => 'عوامري',
            'name' => 'Ouamri',
            'wilaya_id' => '26',
        ],
        [
            'id' => 335,
            'arName' => 'قصر البخاري',
            'name' => 'Ksar El Boukhari',
            'wilaya_id' => '26',
        ],
        [
            'id' => 336,
            'arName' => 'سغوان',
            'name' => 'Seghouane',
            'wilaya_id' => '26',
        ],
        [
            'id' => 337,
            'arName' => 'عشعاشة',
            'name' => 'Achaacha',
            'wilaya_id' => '27',
        ],
        [
            'id' => 338,
            'arName' => 'خير الدين',
            'name' => 'Kheir Eddine',
            'wilaya_id' => '27',
        ],
        [
            'id' => 339,
            'arName' => 'عين نويسي',
            'name' => 'Ain Nouicy',
            'wilaya_id' => '27',
        ],
        [
            'id' => 340,
            'arName' => 'ماسرة',
            'name' => 'Mesra',
            'wilaya_id' => '27',
        ],
        [
            'id' => 341,
            'arName' => 'عين تادلس',
            'name' => 'Ain Tedeles',
            'wilaya_id' => '27',
        ],
        [
            'id' => 342,
            'arName' => 'سيدي لخضر',
            'name' => 'Sidi Lakhdar',
            'wilaya_id' => '27',
        ],
        [
            'id' => 343,
            'arName' => 'بوقيراط',
            'name' => 'Bouguirat',
            'wilaya_id' => '27',
        ],
        [
            'id' => 344,
            'arName' => 'حاسي ماماش',
            'name' => 'Hassi Mameche',
            'wilaya_id' => '27',
        ],
        [
            'id' => 345,
            'arName' => 'مستغانم',
            'name' => 'Mostaganem',
            'wilaya_id' => '27',
        ],
        [
            'id' => 346,
            'arName' => 'سيدي علي',
            'name' => 'Sidi Ali',
            'wilaya_id' => '27',
        ],
        [
            'id' => 347,
            'arName' => 'عين الحجل',
            'name' => 'Ain El Hadjel',
            'wilaya_id' => '28',
        ],
        [
            'id' => 348,
            'arName' => 'عين الملح',
            'name' => 'Ain El Melh',
            'wilaya_id' => '28',
        ],
        [
            'id' => 349,
            'arName' => 'مقرة',
            'name' => 'Magra',
            'wilaya_id' => '28',
        ],
        [
            'id' => 350,
            'arName' => 'بن سرور',
            'name' => 'Ben Srour',
            'wilaya_id' => '28',
        ],
        [
            'id' => 351,
            'arName' => 'سيدي عيسى',
            'name' => 'Sidi Aissa',
            'wilaya_id' => '28',
        ],
        [
            'id' => 352,
            'arName' => 'أولاد سيدي ابراهيم',
            'name' => 'Ouled Sidi Brahim',
            'wilaya_id' => '28',
        ],
        [
            'id' => 353,
            'arName' => 'بوسعادة',
            'name' => 'Bousaada',
            'wilaya_id' => '28',
        ],
        [
            'id' => 354,
            'arName' => 'شلال',
            'name' => 'Chellal',
            'wilaya_id' => '28',
        ],
        [
            'id' => 355,
            'arName' => 'جبل مساعد',
            'name' => 'Djebel Messaad',
            'wilaya_id' => '28',
        ],
        [
            'id' => 356,
            'arName' => 'خبانة',
            'name' => 'Khoubana',
            'wilaya_id' => '28',
        ],
        [
            'id' => 357,
            'arName' => 'حمام الضلعة',
            'name' => 'Hammam Dalaa',
            'wilaya_id' => '28',
        ],
        [
            'id' => 358,
            'arName' => 'أولاد دراج',
            'name' => 'Ouled Derradj',
            'wilaya_id' => '28',
        ],
        [
            'id' => 359,
            'arName' => 'امجدل',
            'name' => 'Medjedel',
            'wilaya_id' => '28',
        ],
        [
            'id' => 360,
            'arName' => 'المسيلة',
            'name' => "M'sila",
            'wilaya_id' => '28',
        ],
        [
            'id' => 361,
            'arName' => 'سيدي عامر',
            'name' => 'Sidi Ameur',
            'wilaya_id' => '28',
        ],
        [
            'id' => 362,
            'arName' => 'عين فارس',
            'name' => 'Ain Fares',
            'wilaya_id' => '29',
        ],
        [
            'id' => 363,
            'arName' => 'عين فكان',
            'name' => 'Ain Fekan',
            'wilaya_id' => '29',
        ],
        [
            'id' => 364,
            'arName' => 'وادي الأبطال',
            'name' => 'Oued El Abtal',
            'wilaya_id' => '29',
        ],
        [
            'id' => 365,
            'arName' => 'عقاز',
            'name' => 'Oggaz',
            'wilaya_id' => '29',
        ],
        [
            'id' => 366,
            'arName' => 'عوف',
            'name' => 'Aouf',
            'wilaya_id' => '29',
        ],
        [
            'id' => 367,
            'arName' => 'سيق',
            'name' => 'Sig',
            'wilaya_id' => '29',
        ],
        [
            'id' => 368,
            'arName' => 'بوحنيفية',
            'name' => 'Bouhanifia',
            'wilaya_id' => '29',
        ],
        [
            'id' => 369,
            'arName' => 'البرج',
            'name' => 'El Bordj',
            'wilaya_id' => '29',
        ],
        [
            'id' => 370,
            'arName' => 'زهانة',
            'name' => 'Zahana',
            'wilaya_id' => '29',
        ],
        [
            'id' => 371,
            'arName' => 'المحمدية',
            'name' => 'Mohammadia',
            'wilaya_id' => '29',
        ],
        [
            'id' => 372,
            'arName' => 'الحشم',
            'name' => 'Hachem',
            'wilaya_id' => '29',
        ],
        [
            'id' => 373,
            'arName' => 'تيزي',
            'name' => 'Tizi',
            'wilaya_id' => '29',
        ],
        [
            'id' => 374,
            'arName' => 'غريس',
            'name' => 'Ghriss',
            'wilaya_id' => '29',
        ],
        [
            'id' => 375,
            'arName' => 'وادي التاغية',
            'name' => 'Oued Taria',
            'wilaya_id' => '29',
        ],
        [
            'id' => 376,
            'arName' => 'معسكر',
            'name' => 'Mascara',
            'wilaya_id' => '29',
        ],
        [
            'id' => 377,
            'arName' => 'تيغنيف',
            'name' => 'Tighennif',
            'wilaya_id' => '29',
        ],
        [
            'id' => 378,
            'arName' => 'سيدي خويلد',
            'name' => 'Sidi Khouiled',
            'wilaya_id' => '30',
        ],
        [
            'id' => 379,
            'arName' => 'الطيبات',
            'name' => 'Taibet',
            'wilaya_id' => '55',
        ],
        [
            'id' => 380,
            'arName' => 'تماسين',
            'name' => 'Temacine',
            'wilaya_id' => '55',
        ],
        [
            'id' => 381,
            'arName' => 'الحجيرة',
            'name' => 'El-Hadjira',
            'wilaya_id' => '55',
        ],
        [
            'id' => 382,
            'arName' => 'البرمة',
            'name' => 'El Borma',
            'wilaya_id' => '30',
        ],
        [
            'id' => 383,
            'arName' => 'حاسي مسعود',
            'name' => 'Hassi Messaoud',
            'wilaya_id' => '30',
        ],
        [
            'id' => 384,
            'arName' => 'المقارين',
            'name' => 'Megarine',
            'wilaya_id' => '55',
        ],
        [
            'id' => 385,
            'arName' => 'تقرت',
            'name' => 'Touggourt',
            'wilaya_id' => '55',
        ],
        [
            'id' => 386,
            'arName' => 'انقوسة',
            'name' => "N'goussa",
            'wilaya_id' => '30',
        ],
        [
            'id' => 387,
            'arName' => 'ورقلة',
            'name' => 'Ouargla',
            'wilaya_id' => '30',
        ],
        [
            'id' => 388,
            'arName' => 'بطيوة',
            'name' => 'Bethioua',
            'wilaya_id' => '31',
        ],
        [
            'id' => 389,
            'arName' => 'بوتليليس',
            'name' => 'Boutlelis',
            'wilaya_id' => '31',
        ],
        [
            'id' => 390,
            'arName' => 'عين الترك',
            'name' => 'Ain Turk',
            'wilaya_id' => '31',
        ],
        [
            'id' => 391,
            'arName' => 'أرزيو',
            'name' => 'Arzew',
            'wilaya_id' => '31',
        ],
        [
            'id' => 392,
            'arName' => 'قديل',
            'name' => 'Gdyel',
            'wilaya_id' => '31',
        ],
        [
            'id' => 393,
            'arName' => 'بئر الجير',
            'name' => 'Bir El Djir',
            'wilaya_id' => '31',
        ],
        [
            'id' => 394,
            'arName' => 'وادي تليلات',
            'name' => 'Oued Tlelat',
            'wilaya_id' => '31',
        ],
        [
            'id' => 395,
            'arName' => 'السانية',
            'name' => 'Es Senia',
            'wilaya_id' => '31',
        ],
        [
            'id' => 396,
            'arName' => 'وهران',
            'name' => 'Oran',
            'wilaya_id' => '31',
        ],
        [
            'id' => 397,
            'arName' => 'الأبيض سيدي الشيخ',
            'name' => 'Labiodh Sidi Cheikh',
            'wilaya_id' => '32',
        ],
        [
            'id' => 398,
            'arName' => 'بوعلام',
            'name' => 'Boualem',
            'wilaya_id' => '32',
        ],
        [
            'id' => 399,
            'arName' => 'بوقطب',
            'name' => 'Bougtoub',
            'wilaya_id' => '32',
        ],
        [
            'id' => 400,
            'arName' => 'بوسمغون',
            'name' => 'Boussemghoun',
            'wilaya_id' => '32',
        ],
        [
            'id' => 401,
            'arName' => 'بريزينة',
            'name' => 'Brezina',
            'wilaya_id' => '32',
        ],
        [
            'id' => 402,
            'arName' => 'رقاصة',
            'name' => 'Rogassa',
            'wilaya_id' => '32',
        ],
        [
            'id' => 403,
            'arName' => 'شلالة',
            'name' => 'Chellala',
            'wilaya_id' => '32',
        ],
        [
            'id' => 404,
            'arName' => 'البيض',
            'name' => 'El Bayadh',
            'wilaya_id' => '32',
        ],
        [
            'id' => 405,
            'arName' => 'جانت',
            'name' => 'Djanet',
            'wilaya_id' => '56',
        ],
        [
            'id' => 406,
            'arName' => 'إن أمناس',
            'name' => 'In Amenas',
            'wilaya_id' => '33',
        ],
        [
            'id' => 407,
            'arName' => 'إيليزي',
            'name' => 'Illizi',
            'wilaya_id' => '33',
        ],
        [
            'id' => 408,
            'arName' => 'عين تاغروت',
            'name' => 'Ain Taghrout',
            'wilaya_id' => '34',
        ],
        [
            'id' => 409,
            'arName' => 'رأس الوادي',
            'name' => 'Ras El Oued',
            'wilaya_id' => '34',
        ],
        [
            'id' => 410,
            'arName' => 'برج بوعريريج',
            'name' => 'Bordj Bou Arreridj',
            'wilaya_id' => '34',
        ],
        [
            'id' => 411,
            'arName' => 'برج الغدير',
            'name' => 'Bordj Ghedir',
            'wilaya_id' => '34',
        ],
        [
            'id' => 412,
            'arName' => 'المنصورة',
            'name' => 'Mansourah',
            'wilaya_id' => '34',
        ],
        [
            'id' => 413,
            'arName' => 'بئر قاصد علي',
            'name' => 'Bir Kasdali',
            'wilaya_id' => '34',
        ],
        [
            'id' => 414,
            'arName' => 'برج زمورة',
            'name' => 'Bordj Zemmoura',
            'wilaya_id' => '34',
        ],
        [
            'id' => 415,
            'arName' => 'جعافرة',
            'name' => 'Djaafra',
            'wilaya_id' => '34',
        ],
        [
            'id' => 416,
            'arName' => 'الحمادية',
            'name' => 'El Hamadia',
            'wilaya_id' => '34',
        ],
        [
            'id' => 417,
            'arName' => 'مجانة',
            'name' => 'Medjana',
            'wilaya_id' => '34',
        ],
        [
            'id' => 418,
            'arName' => 'دلس',
            'name' => 'Dellys',
            'wilaya_id' => '35',
        ],
        [
            'id' => 419,
            'arName' => 'الثنية',
            'name' => 'Thenia',
            'wilaya_id' => '35',
        ],
        [
            'id' => 420,
            'arName' => 'بغلية',
            'name' => 'Baghlia',
            'wilaya_id' => '35',
        ],
        [
            'id' => 421,
            'arName' => 'برج منايل',
            'name' => 'Bordj Menaiel',
            'wilaya_id' => '35',
        ],
        [
            'id' => 422,
            'arName' => 'بودواو',
            'name' => 'Boudouaou',
            'wilaya_id' => '35',
        ],
        [
            'id' => 423,
            'arName' => 'بومرداس',
            'name' => 'Boumerdes',
            'wilaya_id' => '35',
        ],
        [
            'id' => 424,
            'arName' => 'يسر',
            'name' => 'Isser',
            'wilaya_id' => '35',
        ],
        [
            'id' => 425,
            'arName' => 'خميس الخشنة',
            'name' => 'Khemis El Khechna',
            'wilaya_id' => '35',
        ],
        [
            'id' => 426,
            'arName' => 'الناصرية',
            'name' => 'Naciria',
            'wilaya_id' => '35',
        ],
        [
            'id' => 427,
            'arName' => 'الطارف',
            'name' => 'El Tarf',
            'wilaya_id' => '36',
        ],
        [
            'id' => 428,
            'arName' => 'بوحجار',
            'name' => 'Bouhadjar',
            'wilaya_id' => '36',
        ],
        [
            'id' => 429,
            'arName' => 'البسباس',
            'name' => 'Besbes',
            'wilaya_id' => '36',
        ],
        [
            'id' => 430,
            'arName' => 'بن مهيدي',
            'name' => "Ben M'hidi",
            'wilaya_id' => '36',
        ],
        [
            'id' => 431,
            'arName' => 'بوثلجة',
            'name' => 'Bouteldja',
            'wilaya_id' => '36',
        ],
        [
            'id' => 432,
            'arName' => 'الذرعان',
            'name' => 'Drean',
            'wilaya_id' => '36',
        ],
        [
            'id' => 433,
            'arName' => 'القالة',
            'name' => 'El Kala',
            'wilaya_id' => '36',
        ],
        [
            'id' => 434,
            'arName' => 'تندوف',
            'name' => 'Tindouf',
            'wilaya_id' => '37',
        ],
        [
            'id' => 435,
            'arName' => 'عماري',
            'name' => 'Ammari',
            'wilaya_id' => '38',
        ],
        [
            'id' => 436,
            'arName' => 'برج بونعامة',
            'name' => 'Bordj Bounaama',
            'wilaya_id' => '38',
        ],
        [
            'id' => 437,
            'arName' => 'برج الأمير عبد القادر',
            'name' => 'Bordj Emir Abdelkader',
            'wilaya_id' => '38',
        ],
        [
            'id' => 438,
            'arName' => 'الأزهرية',
            'name' => 'Lazharia',
            'wilaya_id' => '38',
        ],
        [
            'id' => 439,
            'arName' => 'خميستي',
            'name' => 'Khemisti',
            'wilaya_id' => '38',
        ],
        [
            'id' => 440,
            'arName' => 'لرجام',
            'name' => 'Lardjem',
            'wilaya_id' => '38',
        ],
        [
            'id' => 441,
            'arName' => 'تيسمسيلت',
            'name' => 'Tissemsilt',
            'wilaya_id' => '38',
        ],
        [
            'id' => 442,
            'arName' => 'ثنية الاحد',
            'name' => 'Theniet El Had',
            'wilaya_id' => '38',
        ],
        [
            'id' => 443,
            'arName' => 'البياضة',
            'name' => 'Bayadha',
            'wilaya_id' => '39',
        ],
        [
            'id' => 444,
            'arName' => 'الطالب العربي',
            'name' => 'Taleb Larbi',
            'wilaya_id' => '39',
        ],
        [
            'id' => 445,
            'arName' => 'الدبيلة',
            'name' => 'Debila',
            'wilaya_id' => '39',
        ],
        [
            'id' => 446,
            'arName' => 'جامعة',
            'name' => 'Djamaa',
            'wilaya_id' => '57',
        ],
        [
            'id' => 447,
            'arName' => 'الرباح',
            'name' => 'Robbah',
            'wilaya_id' => '39',
        ],
        [
            'id' => 448,
            'arName' => 'المغير',
            'name' => 'El Meghaier',
            'wilaya_id' => '57',
        ],
        [
            'id' => 449,
            'arName' => 'الوادي',
            'name' => 'El Oued',
            'wilaya_id' => '39',
        ],
        [
            'id' => 450,
            'arName' => 'قمار',
            'name' => 'Guemar',
            'wilaya_id' => '39',
        ],
        [
            'id' => 451,
            'arName' => 'الرقيبة',
            'name' => 'Reguiba',
            'wilaya_id' => '39',
        ],
        [
            'id' => 452,
            'arName' => 'حاسي خليفة',
            'name' => 'Hassi Khalifa',
            'wilaya_id' => '39',
        ],
        [
            'id' => 453,
            'arName' => 'المقرن',
            'name' => 'Magrane',
            'wilaya_id' => '39',
        ],
        [
            'id' => 454,
            'arName' => 'اميه وانسة',
            'name' => 'Mih Ouensa',
            'wilaya_id' => '39',
        ],
        [
            'id' => 455,
            'arName' => 'عين الطويلة',
            'name' => 'Ain Touila',
            'wilaya_id' => '40',
        ],
        [
            'id' => 456,
            'arName' => 'بابار',
            'name' => 'Babar',
            'wilaya_id' => '40',
        ],
        [
            'id' => 457,
            'arName' => 'الحامة',
            'name' => 'El Hamma',
            'wilaya_id' => '40',
        ],
        [
            'id' => 458,
            'arName' => 'بوحمامة',
            'name' => 'Bouhmama',
            'wilaya_id' => '40',
        ],
        [
            'id' => 459,
            'arName' => 'ششار',
            'name' => 'Chechar',
            'wilaya_id' => '40',
        ],
        [
            'id' => 460,
            'arName' => 'أولاد رشاش',
            'name' => 'Ouled Rechache',
            'wilaya_id' => '40',
        ],
        [
            'id' => 461,
            'arName' => 'قايس',
            'name' => 'Kais',
            'wilaya_id' => '40',
        ],
        [
            'id' => 462,
            'arName' => 'خنشلة',
            'name' => 'Khenchela',
            'wilaya_id' => '40',
        ],
        [
            'id' => 463,
            'arName' => 'سدراتة',
            'name' => 'Sedrata',
            'wilaya_id' => '41',
        ],
        [
            'id' => 464,
            'arName' => 'أولاد إدريس',
            'name' => 'Ouled Driss',
            'wilaya_id' => '41',
        ],
        [
            'id' => 465,
            'arName' => 'بئر بوحوش',
            'name' => 'Bir Bouhouche',
            'wilaya_id' => '41',
        ],
        [
            'id' => 466,
            'arName' => 'تاورة',
            'name' => 'Taoura',
            'wilaya_id' => '41',
        ],
        [
            'id' => 467,
            'arName' => 'الحدادة',
            'name' => 'Haddada',
            'wilaya_id' => '41',
        ],
        [
            'id' => 468,
            'arName' => 'المشروحة',
            'name' => 'Mechroha',
            'wilaya_id' => '41',
        ],
        [
            'id' => 469,
            'arName' => 'مداوروش',
            'name' => "M'daourouche",
            'wilaya_id' => '41',
        ],
        [
            'id' => 470,
            'arName' => 'المراهنة',
            'name' => 'Merahna',
            'wilaya_id' => '41',
        ],
        [
            'id' => 471,
            'arName' => 'أم العظايم',
            'name' => 'Oum El Adhaim',
            'wilaya_id' => '41',
        ],
        [
            'id' => 472,
            'arName' => 'سوق أهراس',
            'name' => 'Souk Ahras',
            'wilaya_id' => '41',
        ],
        [
            'id' => 473,
            'arName' => 'قوراية',
            'name' => 'Gouraya',
            'wilaya_id' => '42',
        ],
        [
            'id' => 474,
            'arName' => 'أحمر العين',
            'name' => 'Ahmar El Ain',
            'wilaya_id' => '42',
        ],
        [
            'id' => 475,
            'arName' => 'بواسماعيل',
            'name' => 'Bou Ismail',
            'wilaya_id' => '42',
        ],
        [
            'id' => 476,
            'arName' => 'القليعة',
            'name' => 'Kolea',
            'wilaya_id' => '42',
        ],
        [
            'id' => 477,
            'arName' => 'الداموس',
            'name' => 'Damous',
            'wilaya_id' => '42',
        ],
        [
            'id' => 478,
            'arName' => 'شرشال',
            'name' => 'Cherchell',
            'wilaya_id' => '42',
        ],
        [
            'id' => 479,
            'arName' => 'فوكة',
            'name' => 'Fouka',
            'wilaya_id' => '42',
        ],
        [
            'id' => 480,
            'arName' => 'حجوط',
            'name' => 'Hadjout',
            'wilaya_id' => '42',
        ],
        [
            'id' => 481,
            'arName' => 'سيدي أعمر',
            'name' => 'Sidi Amar',
            'wilaya_id' => '42',
        ],
        [
            'id' => 482,
            'arName' => 'تيبازة',
            'name' => 'Tipaza',
            'wilaya_id' => '42',
        ],
        [
            'id' => 483,
            'arName' => 'وادي النجاء',
            'name' => 'Oued Endja',
            'wilaya_id' => '43',
        ],
        [
            'id' => 484,
            'arName' => 'عين البيضاء أحريش',
            'name' => 'Ain Beida Harriche',
            'wilaya_id' => '43',
        ],
        [
            'id' => 485,
            'arName' => 'شلغوم العيد',
            'name' => 'Chelghoum Laid',
            'wilaya_id' => '43',
        ],
        [
            'id' => 486,
            'arName' => 'ميلة',
            'name' => 'Mila',
            'wilaya_id' => '43',
        ],
        [
            'id' => 487,
            'arName' => 'ترعي باينان',
            'name' => 'Terrai Bainen',
            'wilaya_id' => '43',
        ],
        [
            'id' => 488,
            'arName' => 'تاجنانت',
            'name' => 'Tadjenanet',
            'wilaya_id' => '43',
        ],
        [
            'id' => 489,
            'arName' => 'بوحاتم',
            'name' => 'Bouhatem',
            'wilaya_id' => '43',
        ],
        [
            'id' => 490,
            'arName' => 'سيدي مروان',
            'name' => 'Sidi Merouane',
            'wilaya_id' => '43',
        ],
        [
            'id' => 491,
            'arName' => 'التلاغمة',
            'name' => 'Teleghma',
            'wilaya_id' => '43',
        ],
        [
            'id' => 492,
            'arName' => 'فرجيوة',
            'name' => 'Ferdjioua',
            'wilaya_id' => '43',
        ],
        [
            'id' => 493,
            'arName' => 'القرارم قوقة',
            'name' => 'Grarem Gouga',
            'wilaya_id' => '43',
        ],
        [
            'id' => 494,
            'arName' => 'تسدان حدادة',
            'name' => 'Tassadane Haddada',
            'wilaya_id' => '43',
        ],
        [
            'id' => 495,
            'arName' => 'الرواشد',
            'name' => 'Rouached',
            'wilaya_id' => '43',
        ],
        [
            'id' => 496,
            'arName' => 'حمام ريغة',
            'name' => 'Hammam Righa',
            'wilaya_id' => '44',
        ],
        [
            'id' => 497,
            'arName' => 'العبادية',
            'name' => 'El Abadia',
            'wilaya_id' => '44',
        ],
        [
            'id' => 498,
            'arName' => 'عين الدفلى',
            'name' => 'Ain Defla',
            'wilaya_id' => '44',
        ],
        [
            'id' => 499,
            'arName' => 'عين الاشياخ',
            'name' => 'Ain Lechiakh',
            'wilaya_id' => '44',
        ],
        [
            'id' => 500,
            'arName' => 'العامرة',
            'name' => 'El Amra',
            'wilaya_id' => '44',
        ],
        [
            'id' => 501,
            'arName' => 'جندل',
            'name' => 'Djendel',
            'wilaya_id' => '44',
        ],
        [
            'id' => 502,
            'arName' => 'بطحية',
            'name' => 'Bathia',
            'wilaya_id' => '44',
        ],
        [
            'id' => 503,
            'arName' => 'مليانة',
            'name' => 'Miliana',
            'wilaya_id' => '44',
        ],
        [
            'id' => 504,
            'arName' => 'برج الأمير خالد',
            'name' => 'Bordj El Emir Khaled',
            'wilaya_id' => '44',
        ],
        [
            'id' => 505,
            'arName' => 'بومدفع',
            'name' => 'Boumedfaa',
            'wilaya_id' => '44',
        ],
        [
            'id' => 506,
            'arName' => 'جليدة',
            'name' => 'Djelida',
            'wilaya_id' => '44',
        ],
        [
            'id' => 507,
            'arName' => 'العطاف',
            'name' => 'El Attaf',
            'wilaya_id' => '44',
        ],
        [
            'id' => 508,
            'arName' => 'الروينة',
            'name' => 'Rouina',
            'wilaya_id' => '44',
        ],
        [
            'id' => 509,
            'arName' => 'خميس',
            'name' => 'Khemis',
            'wilaya_id' => '44',
        ],
        [
            'id' => 510,
            'arName' => 'المشرية',
            'name' => 'Mecheria',
            'wilaya_id' => '45',
        ],
        [
            'id' => 511,
            'arName' => 'عين الصفراء',
            'name' => 'Ain Sefra',
            'wilaya_id' => '45',
        ],
        [
            'id' => 512,
            'arName' => 'عسلة',
            'name' => 'Asla',
            'wilaya_id' => '45',
        ],
        [
            'id' => 513,
            'arName' => 'مغرار',
            'name' => 'Moghrar',
            'wilaya_id' => '45',
        ],
        [
            'id' => 514,
            'arName' => 'مكمن بن عمار',
            'name' => 'Mekmen Ben Amar',
            'wilaya_id' => '45',
        ],
        [
            'id' => 515,
            'arName' => 'النعامة',
            'name' => 'Naama',
            'wilaya_id' => '45',
        ],
        [
            'id' => 516,
            'arName' => 'سفيسيفة',
            'name' => 'Sfissifa',
            'wilaya_id' => '45',
        ],
        [
            'id' => 517,
            'arName' => 'عين الكيحل',
            'name' => 'Ain Kihel',
            'wilaya_id' => '46',
        ],
        [
            'id' => 518,
            'arName' => 'عين الأربعاء',
            'name' => 'Ain Larbaa',
            'wilaya_id' => '46',
        ],
        [
            'id' => 519,
            'arName' => 'عين تموشنت',
            'name' => 'Ain Temouchent',
            'wilaya_id' => '46',
        ],
        [
            'id' => 520,
            'arName' => 'بني صاف',
            'name' => 'Beni Saf',
            'wilaya_id' => '46',
        ],
        [
            'id' => 521,
            'arName' => 'العامرية',
            'name' => 'El Amria',
            'wilaya_id' => '46',
        ],
        [
            'id' => 522,
            'arName' => 'المالح',
            'name' => 'El Maleh',
            'wilaya_id' => '46',
        ],
        [
            'id' => 523,
            'arName' => 'حمام بوحجر',
            'name' => 'Hammam Bou Hadjar',
            'wilaya_id' => '46',
        ],
        [
            'id' => 524,
            'arName' => 'ولهاصة الغرابة',
            'name' => 'Oulhassa Gheraba',
            'wilaya_id' => '46',
        ],
        [
            'id' => 525,
            'arName' => 'بريان',
            'name' => 'Berriane',
            'wilaya_id' => '47',
        ],
        [
            'id' => 526,
            'arName' => 'بونورة',
            'name' => 'Bounoura',
            'wilaya_id' => '47',
        ],
        [
            'id' => 527,
            'arName' => 'ضاية بن ضحوة',
            'name' => 'Dhayet Ben Dhahoua',
            'wilaya_id' => '47',
        ],
        [
            'id' => 528,
            'arName' => 'المنيعة',
            'name' => 'El Menia',
            'wilaya_id' => '58',
        ],
        [
            'id' => 529,
            'arName' => 'غرداية',
            'name' => 'Ghardaia',
            'wilaya_id' => '47',
        ],
        [
            'id' => 530,
            'arName' => 'القرارة',
            'name' => 'El Guerrara',
            'wilaya_id' => '47',
        ],
        [
            'id' => 531,
            'arName' => 'المنصورة',
            'name' => 'Mansourah',
            'wilaya_id' => '58',
        ],
        [
            'id' => 532,
            'arName' => 'المنصورة',
            'name' => 'Mansourah',
            'wilaya_id' => '47',
        ],
        [
            'id' => 533,
            'arName' => 'متليلي',
            'name' => 'Metlili',
            'wilaya_id' => '47',
        ],
        [
            'id' => 534,
            'arName' => 'زلفانة',
            'name' => 'Zelfana',
            'wilaya_id' => '47',
        ],
        [
            'id' => 535,
            'arName' => 'يلل',
            'name' => 'Yellel',
            'wilaya_id' => '48',
        ],
        [
            'id' => 536,
            'arName' => 'عين طارق',
            'name' => 'Ain Tarek',
            'wilaya_id' => '48',
        ],
        [
            'id' => 537,
            'arName' => 'عمي موسى',
            'name' => 'Ammi Moussa',
            'wilaya_id' => '48',
        ],
        [
            'id' => 538,
            'arName' => 'المطمر',
            'name' => 'El Matmar',
            'wilaya_id' => '48',
        ],
        [
            'id' => 539,
            'arName' => 'غليزان',
            'name' => 'Relizane',
            'wilaya_id' => '48',
        ],
        [
            'id' => 540,
            'arName' => 'زمورة',
            'name' => 'Zemmoura',
            'wilaya_id' => '48',
        ],
        [
            'id' => 541,
            'arName' => 'سيدي أمحمد بن علي',
            'name' => "Sidi M'hamed Ben Ali",
            'wilaya_id' => '48',
        ],
        [
            'id' => 542,
            'arName' => 'جديوية',
            'name' => 'Djidiouia',
            'wilaya_id' => '48',
        ],
        [
            'id' => 543,
            'arName' => 'الحمادنة',
            'name' => "El H'madna",
            'wilaya_id' => '48',
        ],
        [
            'id' => 544,
            'arName' => 'مازونة',
            'name' => 'Mazouna',
            'wilaya_id' => '48',
        ],
        [
            'id' => 545,
            'arName' => 'وادي رهيو',
            'name' => 'Oued Rhiou',
            'wilaya_id' => '48',
        ],
        [
            'id' => 546,
            'arName' => 'منداس',
            'name' => 'Mendes',
            'wilaya_id' => '48',
        ],
        [
            'id' => 547,
            'arName' => 'الرمكة',
            'name' => 'Ramka',
            'wilaya_id' => '48',
        ],
    ];

    public function run()
    {
        array_walk($this->dairas, function ($daira) {
            Daira::create($daira);
        });
    }
}
